[package]
name = "object_store"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdb@service.alipay.com>"]
edition = "2018"

[dependencies]
upstream = { package = "object_store", version =  "0.1.0" }
