[package]
name = "sql"
version = "0.1.0"
authors = ["CeresDB Authors <ceresdb@service.alipay.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test = []

[dependencies]
# In alphabetical order
arrow_deps = { path = "../arrow_deps" }
catalog = { path = "../catalog" }
common_types = { path = "../common_types"}
common_util = { path = "../common_util" }
log = "0.4"
paste = "1.0"
snafu = { version ="0.6.10", features = ["backtraces"]}
sqlparser = "0.18.0"
table_engine = { path = "../table_engine" }
df_operator = { path = "../df_operator" }
ceresdbproto = { git = "https://github.com/CeresDB/ceresdbproto.git"}
regex = "1"

[dev-dependencies]
common_types = { path = "../common_types", features = ["test"] }
tokio = { version = "1.0", features = ["full"] }
