name: Build Docker Image without Pushing

on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build CeresDB Server Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ceresdb/ceresdb-server:${{github.ref_name}}
